services:
  - type: web
    name: tims-backend
    env: node
    region: "oregon"
    branch: "main"
    root: "tool-system"
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: "free"
